# config/packages/knp_paginator.yaml
knp_paginator:
    page_range: 5          # How many pages to display in pagination widget
    default_options:
        page_name: page    # Page query parameter name
        sort_field_name: sort  # Sort query parameter name
        sort_direction_name: direction   # Sort direction query parameter name
        distinct: true     # Ensure distinct results (useful with GROUP BY statements)
    template:
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig'  # Bootstrap 4 pagination
