vich_uploader:
    db_driver: orm
    mappings:
        video:
            uri_prefix: '/uploads/files'
            upload_destination: '%kernel.project_dir%/public/uploads/files'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
        products:
            uri_prefix: '%product_attachments%'
            upload_destination: '%kernel.project_dir%/public%product_attachments%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
        profile_pictures:  
            uri_prefix: '/uploads/profile_pictures'
            upload_destination: '%kernel.project_dir%/public/uploads/profile_pictures' 
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer  
            delete_on_update: true  
            delete_on_remove: true 
        image_voiture:
            uri_prefix: '%img_voiture%'
            upload_destination: '%kernel.project_dir%/public%img_voiture%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
        image:
            uri_prefix: '%img_brand%'
            upload_destination: '%kernel.project_dir%/public%img_brand%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
       
