# config/routes.yaml

# Import all routes defined in controller classes using attributes
controllers:
    resource: '../src/Controller/'
    type: attribute
change_language:
    path: /change-language
    controller: App\Controller\LanguageController::changeLanguage
    methods: [POST]

